### ISSUE TITLE
run on cpus or gpus?

### ISSUE THREAD

**Issue by huangnengCSU** [parlance/ctcdecode#100]
the BeamCTCDecoder run using cpus or gpus?

**Comment by lukhy** [comment]
as far as I see, it's on cpu

**Comment by huangnengCSU** [comment]
> as far as I see, it's on cpu

Can CTCBeamsearch be executed in multiple threads?

**Comment by primejava** [comment]
install it need cuda

**Comment by SeanNaren** [comment]
Yes! You can specify the number of processes to automatically multi-process your batch. As mentioned it only uses the CPU currently.
