### ISSUE TITLE
How to increase the decode speed?

### ISSUE THREAD

**Issue by anhle-uet** [parlance/ctcdecode#104]
I'm using CTCBeamDecoder with default setttings. num_processes=10, max sequence length is 37 and the size of lexicon is around 3000 characters. The decoding speed is kinda slow now.

**Comment by animebing** [comment]
@anhle-uet change `cutoff_prob` to `log_cutoff_prob` in [this line](https://github.com/parlance/ctcdecode/blob/master/ctcdecode/src/decoder_utils.cpp#L22), and you'd better set `cutoff_prob` less than 1.0 (such as 0.99) in `__init__` of `CTCBeamDecoder`.

**Comment by anhle-uet** [comment]
Thanks, I'll try it out.
