### ISSUE TITLE
Wrong cutoff_prob comparison in pruning

### ISSUE THREAD

**Issue by vadimkantorov** [parlance/ctcdecode#113]
https://github.com/parlance/ctcdecode/blob/master/ctcdecode/src/decoder_utils.cpp#L22

`cutoff_prob` is checked to be less than zero (which never holds). I think it was meant to compare `log_cutoff_prob` with zero.

This effectively disables `cutoff_prob` and `cutoff_top_n` pruning.

After this fix, there is another bug: `cutoff_top_n` pruning is always disabled if `cutoff_prob == 1.0`. cutoff_prob == 0.9999 as a workaround.

**Comment by yuetz** [comment]
I had a pr to solve this bug.
https://github.com/parlance/ctcdecode/pull/107#issue-293201427
