### ISSUE TITLE
Segmentation Fault in CTCBeamDecoder

### ISSUE THREAD

**Issue by shivam2298** [parlance/ctcdecode#121]
I am getting these errors 

> Segmentation fault (core dumped)
> $ python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 20 leaked semaphores to clean up at shutdown
>   len(cache))

I am getting this when I pass the prob matrix in decode function of a BeamSearchDecoder object.

python 3.7
torch 1.1.0

**Comment by rajeevbaalwan** [comment]
@shivam2298 was your resolved ??
I am also getting segmentation fault with pytorch 1.3.0

  0%|                                                                                                                                                      | 0/12500 [00:00<?, ?it/s]Segmentation fault (core dumped)
