### ISSUE TITLE
TypeError: paddle_get_scorer(): incompatible function arguments. The following argument types are supported:     1. (arg0: float, arg1: float, arg2: str, arg3: List[str], arg4: int) -> capsule

### ISSUE THREAD

**Issue by ilove-Moretz** [parlance/ctcdecode#146]
Why this error happens?

**Comment by ylsxw** [comment]
I have this problem, too

**Comment by fanliukund** [comment]
I have this problem, too

**Comment by SeanNaren** [comment]
Can anyone give me the tracelog of what they're running to see this error?

**Comment by fanliukund** [comment]
Loading model...
Traceback (most recent call last):
&nbsp; File "examples/demo-server.py", line 9, in <module&gt;
&nbsp; &nbsp; import beamdecode
&nbsp; File "/Users/BBC/AIProjects/masr/examples/../beamdecode.py", line 29, in <module&gt;
&nbsp; &nbsp; blank_index,
&nbsp; File "/usr/local/lib/python3.7/site-packages/ctcdecode/__init__.py", line 18, in __init__
&nbsp; &nbsp; self._num_labels)
TypeError: paddle_get_scorer(): incompatible function arguments. The following argument types are supported:
&nbsp; &nbsp; 1. (arg0: float, arg1: float, arg2: str, arg3: List[str], arg4: int) -&gt; capsule






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sean Naren"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月7日(星期天) 凌晨0:32
收件人:&nbsp;"parlance/ctcdecode"<ctcdecode@noreply.github.com&gt;;
抄送:&nbsp;"♂AB℃』"<276521682@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [parlance/ctcdecode] TypeError: paddle_get_scorer(): incompatible function arguments. The following argument types are supported:     1. (arg0: float, arg1: float, arg2: str, arg3: List[str], arg4: int) -&gt; capsule (#146)





 
Can anyone give me the tracelog of what they're running to see this error?

**Comment by SeanNaren** [comment]
Can you guys try installing this branch and seeing if it works: https://github.com/parlance/ctcdecode/tree/feature/labels_list

**Comment by fanliukund** [comment]
It works, thank you for timely repair.

**Comment by SeanNaren** [comment]
Thanks guys, merged into master! closing this issue
