### ISSUE TITLE
Proplem at "pip install ."

### ISSUE THREAD

**Issue by ilove-Moretz** [parlance/ctcdecode#151]
When I use command "pip install ."，some error happen,the error log is:

> ERROR: Command errored out with exit status 1: /home/user/anaconda3/envs/wbq_base/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-g33nhm_8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-g33nhm_8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-77ie84d6/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/anaconda3/envs/wbq_base/include/python3.7m/ctcdecode Check the logs for full command output.

When I check the log，I find this：

>  ctcdecode/src/decoder_utils.h:8:21: fatal error: fst/log.h:

it seems that the openfst did not install successfully. 

What should I do to deal this error?Thanks
-----------------------------------------------------------------------
ok，I have solved this problem. I will closs this issue

**Comment by SeanNaren** [comment]
How did you solve this?

**Comment by ilove-Moretz** [comment]
> 
> 
> How did you solve this?
My serve can not connect google to download openfst-1.6.7.tar.gz. So I download openfst-1.6.7.tar.gz and upload it to my serve.But I forget unzip the file,so the error happend. After unzip the openfst-1.6.7.tar.gz, it installed successfully
