### ISSUE TITLE
New Readme with Explanations

### ISSUE THREAD

**Issue by rbracco** [parlance/ctcdecode#155]
As a user I found this library very hard to get started with due to the limited README. I learned a lot in trying to make it work and would be happy to PR a more detailed readme. Before I do I want to make sure
1. this is something that is wanted
2. more experienced devs would be willing to answer a few questions such as "what do the beam scores represent?". My best guess is that P(beam[i]) = 1/(e^beam_score[i]) but I really have no idea.

Please let me know if this would be useful and I will submit a WIP PR.

**Comment by SeanNaren** [comment]
More than happy to collab on this, explicit READMEs always help 👍

**Comment by rbracco** [comment]
Awesome, thank you for your work on DeepSpeech by the way! I'll work on a README and PR a WIP once I have a draft. I just want to confirm PRs are still getting merged, then I'll close the issue.

**Comment by SeanNaren** [comment]
Thanks for the kind words :) feel free to keep this issue open to track the new READMe, and let me know when you need me to take a look/add things in!

**Comment by LordOfLuck** [comment]
I also would be grateful for more detailed readme or some docs in the python code. :)

**Comment by rbracco** [comment]
Added WIP Readme PR #157
