### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by Syedwajihshah** [parlance/ctcdecode#178]
cd ctcdecode && pip install .
Processing /home/wajih/learning/ctcdecode
    ERROR: Command errored out with exit status 1:
     command: /home/wajih/.virtualenvs/ctcdec/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-l63htf6e/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-l63htf6e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-deeuyeyg
         cwd: /tmp/pip-req-build-l63htf6e/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-l63htf6e/setup.py", line 10, in <module>
        from torch.utils.cpp_extension import BuildExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Syedwajihshah** [comment]
Installed pytorch before installing this. Fixed the issue.

**Comment by jubick1337** [comment]
This isn't fix it's a workaround
This must be fixed by developer because other package managers don't see torch as requirement for ctcdecode
