### ISSUE TITLE
beam decode got strange index number.

### ISSUE THREAD

**Issue by phecda-xu** [parlance/ctcdecode#187]
hello:

strange decode result such as : [[235, 324, 128,....,10000000834264,-1024295105]]

number 10000000834264 and -1024295105 are out of vocabliary.

I think it is refer to here
https://github.com/parlance/ctcdecode/blob/9a20e00f34d8f605f4a8501cc42b1a53231f1597/ctcdecode/__init__.py#L70

`torch.IntTensor([])` will init a tensor with many  large number (postive or negative).
 so, why not use 0, just like `torch.IntTensor([]).zero_()`?

Thanks, hope your reply!

**Comment by masakistan** [comment]
@phecda-xu , what ended up being the issue? I seem to be running into this as well.

**Comment by cqray1990** [comment]
@phecda-xu i meet that too,how did exclude the arge number?
