### ISSUE TITLE
Pip install issues - macOS

### ISSUE THREAD

**Issue by Magnuslyk** [parlance/ctcdecode#198]
Im running Apple clang version 12.0.5 (clang-1205.0.22.9), tried both python 3.9, 3.8, 3.6. Ive tried torch 1.4 and 1.10. 
Im running into the same problem everytime;  `ERROR: Failed building wheel for ctcdecode. `

The error message is veeeery long, but the top of it looks like this: 

`ERROR: Command errored out with exit status 1:
   command: /Users/magnuslyk/opt/miniconda3/envs/xtech/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/40/mvywxcyx5h5463679qv4g3780000gn/T/pip-req-build-r9pb__ba/setup.py'"'"'; __file__='"'"'/private/var/folders/40/mvywxcyx5h5463679qv4g3780000gn/T/pip-req-build-r9pb__ba/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/40/mvywxcyx5h5463679qv4g3780000gn/T/pip-wheel-6rgarvb_
       cwd: /private/var/folders/40/mvywxcyx5h5463679qv4g3780000gn/T/pip-req-build-r9pb__ba/
  Complete output (7260 lines):
  /Users/magnuslyk/opt/miniconda3/envs/xtech/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'package', 'with_cuda'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/ctcdecode
  copying ctcdecode/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/ctcdecode
  running build_ext
... `

I have been going through all issue postings with similar problems, and it seems the issue on macOS persists. 
Can anyone help with this?

**Comment by DanTremonti** [comment]
Try executing
`pip install git+https://github.com/parlance/ctcdecode`

**Comment by chandralegend** [comment]
bump
