### ISSUE TITLE
How to use timesteps information to calculate word-level alignments?

### ISSUE THREAD

**Issue by abarcovschi** [parlance/ctcdecode#225]
I am trying to create word-level time alignments from the output of the beam search decoder, but I am not sure how to use the timesteps field to calculate this information. Could anyone please provide some formula or code implementation on how to convert the timesteps into word-level time alignments? I would be extremely grateful for any pointers!

**Comment by farisalasmary** [comment]
Hi @abarcovschi,

You can use this library to get the word boundaries
https://github.com/lumaku/ctc-segmentation

**Comment by abarcovschi** [comment]
Thank you!
