### ISSUE TITLE
Incorrect maintaining of states for words?

### ISSUE THREAD

**Issue by SeanNaren** [parlance/ctcdecode#33]
One of our colleagues got in touch with @willfrey and he mentioned an issue with the pytorch-ctc implementation:

```
He pointed out that the scorer in pytorch-ctc wasn't maintaining state between words properly, rendering it a "spell checker" (only scoring unigrams basically)
```
I'll do some investigation into this claim and report back!

**Comment by ryanleary** [comment]
This is definitively true. Fix incoming.
