### ISSUE TITLE
_ctc_decode import issue

### ISSUE THREAD

**Issue by eturner303** [parlance/ctcdecode#35]
Hello,

I am still experiencing the _ctc_decode import issue, with the latest pytorch-ctc checkout from the Git repository.

The relevant error lines are:

# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import pytorch_ctc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pytorch_ctc/__init__.py", line 4, in <module>
    from ._ctc_decode import lib as _lib, ffi as _ffi
SystemError: dynamic module not initialized properly
>>>

**Comment by ryanleary** [comment]
I think this may be resolved if using the latest pytorch_ctc and latest pytorch (current master branch). @SeanNaren has some more details on this one.

**Comment by ryanleary** [comment]
Check that -- @SeanNaren has a branch that addresses this. It will be contingent on a change in the master version of pytorch.

**Comment by SeanNaren** [comment]
The newest build system should now work for python 2.7 using the master branch.
