### ISSUE TITLE
AttributeError: 'int' object has no attribute '__module__'

### ISSUE THREAD

**Issue by marcoleewow** [parlance/ctcdecode#43]
I followed your installation guide in a fresh ubuntu 16.04 pyTorch docker and I have this problem when I tried to `import ctcdecode`. Any ideas how to fix it?
![screen shot 2017-11-08 at 3 28 48 pm](https://user-images.githubusercontent.com/22629621/32536469-906d8ee0-c499-11e7-8af5-004d6b923d3b.png)

**Comment by ryanleary** [comment]
We are waiting on a change in pytorch for python2 to work properly. The next version of pytorch released will have the fix.

**Comment by SeanNaren** [comment]
The master branch should now support 2.7
