### ISSUE TITLE
Why ngrams with Out Of Vocabulary words are discarded?

### ISSUE THREAD

**Issue by ankitmundada** [parlance/ctcdecode#49]
I am confused as to why is [this](https://github.com/parlance/ctcdecode/blob/master/ctcdecode/src/scorer.cpp#L83-L85) necessary? 
Scoring any Ngram with a low value when an OOV is encountered means that even if someone's name that is not in the vocabulary will be discarded by the ctcdecoder.

**Comment by ryanleary** [comment]
We could make the OOV score configurable if that's something that would be helpful for you. The point of that is to, as you pointed out, more or less only allow in-vocabulary words to be emitted unless the acoustic model is VERY confident. With a strong word-language model, this tends to work well to reduce EER. You are correct that it hurts performance on things like names. If that's a use case for you, we could also look into adding a configurable list of unigrams whose probabilities would be boosted (ie a set of names etc) or you could train a more tailored language model.

**Comment by PabloValverde** [comment]
Hi, any update on the possibility to boost a list of words as some kind of custom vocabulary which would bias the beam search? Or would you have a suggestion on a workaround to achieve this kind of result? I tried changing log probabilities in the lm arpa file but the results are disappointing
