### ISSUE TITLE
Making the vocabulary trie

### ISSUE THREAD

**Issue by mineshmathew** [parlance/ctcdecode#59]
@ryanleary  I was trying to work with your fork at https://github.com/ryanleary/ctcdecode.
The vanilla decoder works like a charm. But I cant figure out how the trie is being made using the function you mentioned in the README. 

```
import pytorch_ctc
 
lexicon = '~/language_modelling/Jaderberg_90k_lexicon.txt'
output_path = '~/tries/4gram_JaderbergLexicon/'
kenlm_path = '~/language_modelling/lm_4gram_on_lob_and_brown.klm'
labels = '_0123456789abcdefghijklmnopqrstuvwxyz '

pytorch_ctc.generate_lm_trie(lexicon, kenlm_path, output_path, labels, 0, 37)
```

Above is my script to generate the trie . The script runs without any errors. But nothing is being created at the specified  output path

Could you please tell me If I am doing it right

**Comment by ryanleary** [comment]
The trie is no longer needed. Please be sure to use the latest version of this repo.

**Comment by mineshmathew** [comment]
@ryanleary  Would you please  point me to some help/document on how I can use this ? On your fork there was some write up on the functions to be used and the arguments. But I dont see anything here
