### ISSUE TITLE
ImportError in mac

### ISSUE THREAD

**Issue by Marsxia** [parlance/ctcdecode#78]
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctcdecode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marxia/anaconda3/envs/py2/lib/python2.7/site-packages/ctcdecode/__init__.py", line 1, in <module>
    from ._ext import ctc_decode
  File "/Users/marxia/anaconda3/envs/py2/lib/python2.7/site-packages/ctcdecode/_ext/ctc_decode/__init__.py", line 3, in <module>
    from ._ctc_decode import lib as _lib, ffi as _ffi
ImportError: dlopen(/Users/marxia/anaconda3/envs/py2/lib/python2.7/site-packages/ctcdecode/_ext/ctc_decode/_ctc_decode.so, 2): Symbol not found: __ZNSt12future_errorD1Ev
  Referenced from: /Users/marxia/anaconda3/envs/py2/lib/python2.7/site-packages/ctcdecode/_ext/ctc_decode/_ctc_decode.so
  Expected in: flat namespace
 in /Users/marxia/anaconda3/envs/py2/lib/python2.7/site-packages/ctcdecode/_ext/ctc_decode/_ctc_decode.so

**Comment by ryanleary** [comment]
Try with python3 please.

**Comment by Marsxia** [comment]
Hi，you can see the problem #73  when i try with python3
