### ISSUE TITLE
why BeamCTCDecoder have a worse performance than GreedyDecoder?

### ISSUE THREAD

**Issue by huangnengCSU** [parlance/ctcdecode#93]
Hi:
I used the GreedyDecoder()，the result is right and cer is around 10. Then I want to use BeamCTCDecoder() to get better performance. But the result is very bad. CER is around 200. I found the initial beam_size equals to 100, but the max length of my reference sequence is 70. So I change the beam_size to 10. I wonder how set the parameters of BeamCTCDecoder. And why the result of BeamCTCDecoder is worse than GreedyDecoder.

**Comment by vaibhav0195** [comment]
Hi can you explain how you solved the issue ?

**Comment by huangnengCSU** [comment]
> Hi can you explain how you solved the issue ?
Because my output is already log(.) and in the beamsearch I do the log(.) again, actually it only needs one log() operation.
